/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type Language = 'en' | 'hi';

export const TRANSLATIONS = {
  en: {
    dashboard: "Dashboard",
    inventory: "Inventory",
    billing: "Billing",
    reports: "Reports",
    profile: "Profile",
    welcome: "Hello",
    today_profit: "Today's Profit",
    today_sales: "Today's Sales",
    monthly_sales: "Monthly Sales",
    total_products: "Total Products",
    low_stock: "Low Stock",
    create_bill: "Create Bill",
    add_product: "Add Product",
    view_charts: "View Charts",
    daily_target: "Daily Target Tracker",
    remaining: "Remaining",
    target_met: "Target Met!",
    weekly_trend: "Weekly Sales Trend",
    top_selling: "Top Selling Items",
    critical_alerts: "Critical Stock Alerts",
    requires_restock: "Requires Restock",
    udhaar_book: "Udhaar Book",
    customers: "Customers",
    suppliers: "Suppliers",
    employees: "Employees",
    marketing: "Marketing",
    insights: "AI Insights",
    search: "Search...",
    name: "Name",
    mobile: "Mobile",
    save: "Save",
    cancel: "Cancel",
    outstanding: "Outstanding Balance",
    loyalty_points: "Loyalty Points",
    credit_limit: "Credit Limit",
    payment_history: "Payment History",
    add_credit: "Add Credit (Udhaar)",
    record_payment: "Record Payment",
    amount: "Amount (₹)",
    description: "Description",
    date: "Date",
    reminder: "Send Reminder",
    whatsapp_share: "Share on WhatsApp",
    download_invoice: "Download PDF",
    print_invoice: "Print Receipt",
    attendance: "Attendance",
    attendance_marked: "Attendance Recorded",
    sales_target: "Sales Target",
    active: "Active",
    inactive: "Inactive",
    marketing_center: "Promotion Center",
    current_offers: "Current Offers & Campaigns",
    create_campaign: "Launch Discount Campaign",
    supplier_orders: "Purchase Orders & Restock",
    create_po: "Create Purchase Order",
    revenue_pred: "7-Day Revenue Prediction",
    demand_forecast: "Demand Forecasting & Recommendations",
    best_sellers: "AI Best-Selling Recommendations",
    pin_security: "SaaS Security Lock",
    enter_pin: "Enter your 4-digit PIN",
    biometric: "Simulate Biometric Fingerprint ID",
    quick_ops: "Quick Counter Operations",
    all_stocks_safe: "All stocks safe",
    scan_interface: "Barcode Scanning",
    generate_barcode: "Generate Barcode",
    expiry_tracking: "Expiry Date Tracking",
    low_stock_thres: "Low Stock Threshold",
    cost_price: "Cost Price (₹)",
    selling_price: "Selling Price (₹)"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    inventory: "स्टॉक / सूची",
    billing: "बिलिंग (पर्ची)",
    reports: "रिपोर्ट्स",
    profile: "प्रोफ़ाइल",
    welcome: "नमस्ते",
    today_profit: "आज का मुनाफ़ा",
    today_sales: "आज की बिक्री",
    monthly_sales: "मासिक बिक्री",
    total_products: "कुल उत्पाद",
    low_stock: "कम स्टॉक",
    create_bill: "बिल बनाएं",
    add_product: "नया आइटम",
    view_charts: "चार्ट देखें",
    daily_target: "दैनिक बिक्री लक्ष्य",
    remaining: "बचा हुआ",
    target_met: "लक्ष्य पूरा हुआ!",
    weekly_trend: "साप्ताहिक बिक्री ट्रेंड",
    top_selling: "सबसे ज़्यादा बिकने वाले सामान",
    critical_alerts: "गंभीर चेतावनी",
    requires_restock: "स्टॉक भरें",
    udhaar_book: "उधार खाता",
    customers: "ग्राहक सूची",
    suppliers: "सप्लायर्स",
    employees: "कर्मचारी",
    marketing: "प्रचार केंद्र",
    insights: "AI सुझाव",
    search: "खोजें...",
    name: "नाम",
    mobile: "मोबाइल",
    save: "सुरक्षित करें",
    cancel: "रद्द करें",
    outstanding: "कुल बकाया उधार",
    loyalty_points: "लॉयल्टी पॉइंट्स",
    credit_limit: "उधार सीमा",
    payment_history: "भुगतान का इतिहास",
    add_credit: "उधार जोड़ें",
    record_payment: "जमा राशि जोड़ें",
    amount: "राशि (₹)",
    description: "विवरण",
    date: "तारीख",
    reminder: "याद दिलाएं (Reminder)",
    whatsapp_share: "व्हाट्सएप पर शेयर करें",
    download_invoice: "पर्ची डाउनलोड करें",
    print_invoice: "रसीद प्रिंट करें",
    attendance: "हाजिरी (Attendance)",
    attendance_marked: "हाजिरी लग गई",
    sales_target: "बिक्री लक्ष्य",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    marketing_center: "मार्केटिंग अभियान",
    current_offers: "सक्रिय ऑफर्स और छूट",
    create_campaign: "नया ऑफर शुरू करें",
    supplier_orders: "सप्लायर ऑर्डर और स्टॉक",
    create_po: "नया ऑर्डर भेजें",
    revenue_pred: "7-दिवसीय बिक्री का पूर्वानुमान",
    demand_forecast: "मांग का अनुमान और सुझाव",
    best_sellers: "AI बेस्ट-सेलिंग उत्पाद",
    pin_security: "सुरक्षा पिन लॉक",
    enter_pin: "अपना 4-अंकीय पिन दर्ज करें",
    biometric: "बायोमेट्रिक फिंगरप्रिंट की जांच",
    quick_ops: "त्वरित काउंटर संचालन",
    all_stocks_safe: "सभी स्टॉक सुरक्षित हैं",
    scan_interface: "बारकोड स्कैनिंग",
    generate_barcode: "बारकोड तैयार करें",
    expiry_tracking: "समाप्ति तिथि (Expiry) ट्रैकिंग",
    low_stock_thres: "न्यूनतम सीमा",
    cost_price: "खरीद मूल्य (₹)",
    selling_price: "बिक्री मूल्य (₹)"
  }
} as const;

export function t(key: keyof typeof TRANSLATIONS['en'], lang: Language): string {
  const dictionary = TRANSLATIONS[lang] || TRANSLATIONS['en'];
  return (dictionary[key] || TRANSLATIONS['en'][key]) as string;
}
